### ISSUE TITLE
Unable to unzip dataset archive

### ISSUE THREAD

**Issue by mfox94** [tqtg/hierarchical-attention-networks#1]
There is a problem in unzipping the zip file into the 7z archive to download for the dataset. 
Can you resolve and publish it in a mirror?

**Comment by qtuantruong** [comment]
Hi @mfox94 
I guess you may need to use 7-Zip (https://www.7-zip.org/) to unzip the file.

**Comment by mfox94** [comment]
Hi @tqtg 
7zip displays the message error of _file damaged_.
The problem happens only when I try to unzip the zip file, not the 7z file. I think there is a problem in the compression of the latter one. 
Could you upload the archive without this problem, please? Maybe on Google drive for a faster download..

**Comment by qtuantruong** [comment]
> Hi @tqtg
> 7zip displays the message error of _file damaged_.
> The problem happens only when I try to unzip the zip file, not the 7z file. I think there is a problem in the compression of the latter one.
> Could you upload the archive without this problem, please? Maybe on Google drive for a faster download..

Could you provide me the link that causes the problem?

FYI: the datasets (EMNLP'15 paper) are provided by Duyu Tang from his homepage http://ir.hit.edu.cn/~dytang/

**Comment by mfox94** [comment]
http://ir.hit.edu.cn/~dytang/paper/emnlp2015/emnlp-2015-data.7z

**Comment by qtuantruong** [comment]
@mfox94 I uploaded the data to GG Drive (please request for access): https://drive.google.com/file/d/1OQ_ggjlNUWiTg_zFXc0_OpYXpJRwJP3y

**Comment by mfox94** [comment]
Thank you very much, it seems work!
