### ISSUE TITLE
concating double fw outputs

### ISSUE THREAD

**Issue by yanyang729** [tqtg/hierarchical-attention-networks#2]
https://github.com/tqtg/hierarchical-attention-networks/blob/9b26f087270b69c39844b60e9e2c564eb4f3e5a3/layers.py#L26

**Comment by qtuantruong** [comment]
Thank you for pointing out the issue @yanyang729 !
I fixed the code and re-trained the model. The new results that I got for Yelp-2015 dataset are:
- **69.79%** accuracy on the *dev set*
- **69.62%** accuracy on the *test set*
