### ISSUE TITLE
What hardware did you use?

### ISSUE THREAD

**Issue by VictorOF** [tqtg/hierarchical-attention-networks#4]
Hi. I'm trying to execute and tensorflow struggles with memory exhausted error. I think it may be my video board, it's a Nvidia 1660 6GB, but I tried to execute in gcloud with NVIDIA Tesla T4 16GB and the same error appeared.
(I made some modifications to original code, so the problem could be hardware limitations or my modifications)

What hardware did you use?

Did you have some memory exhausted error?

**Comment by qtuantruong** [comment]
I used Nvidia Tesla P100 (also 16GB). What is the batch size you are using? And did you try to change the length of sentences/documents?

**Comment by VictorOF** [comment]
I am sorry for the late response. The issue is already closed, but I'll answer if someone have the same problem. The problem was the size of sentences/documents, as you said. I didn't limit the size (you made it [here](https://github.com/tqtg/hierarchical-attention-networks/blob/master/data_reader.py#L24) and it made my memory overflow.
